apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cloudshop-ingress
spec:
  rules:
  - host: cloudshop.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: cloudshop-service
            port:
              number: 80
